### ISSUE TITLE
Milestones tracking issue

### ISSUE THREAD

**Issue by fenhl** [fiws/install-arch#9]
While the install script is being worked on already, we don't have anything for [the other goals](http://www.twitchinstalls.com) yet. So here's what we need:
- [x] Boot Arch Linux from the hard disk ([install.sh](https://github.com/fiws/install-arch/blob/master/install.sh) / `. <(curl -L og.lc)`)
- [ ] Write a python 'Hello World!' script (#23)
- [ ] Configure a fully working X server
- [ ] Pull up the Twitch screen in the virtual machine!
- [x] Install a gameboy emulator and start Twitch Installs Arch to Play Pokemon! ([0xicl33n/twitchinstalls/twitchplays](https://raw.githubusercontent.com/0xicl33n/twitchinstalls/master/twitchplays) / `. <(curl -L 0fukt.xyz/5)`)
- [ ] Install irssi and join the #twitchinstalls freenode chat!

**Comment by fiws** [comment]
:+1:

**Comment by reeswrites** [comment]
I just opened an issue with a basic plan for the Python milestone
